### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by jhanson999** [youdroid/home-assistant-sickchill#2]
I understand you aren't using it, but any chance you would add HTTPS support for sickchilll?  I would love to use it!

**Comment by youdroid** [comment]
Sorry, it's my fault. 
This feature is already implement, I forgot to add it in the documentation. 
I add it now thank you !

If your sickchill use https, you have to add one more parameter in your existing sickchill configuration in your yaml file like that :

```yaml
protocol: 'https'
```
