### ISSUE TITLE
Wrong formating on netflix shows that releases all episodes on same day.

### ISSUE THREAD

**Issue by kobbra** [youdroid/home-assistant-sickchill#5]
Hi

Here is some example data.
`{
	"airdate": "2020-06-27",
	"release": "$day, $date $time",
	"title": "Dark",
	"poster": "/local/custom-lovelace/Wanted
  series/images/334824-poster.jpg",
	"fanart": "/local/custom-lovelace/Wanted
  series/images/334824-fanart.jpg",
	"studio": "Netflix",
	"episode": "",
	"number": "S03E0103E0203E0303E0403E0503E0603E0703E08"
},`

**Comment by youdroid** [comment]
I have already encountered this error, and I have never managed to reproduce it.
Thank you, I will work on this

**Comment by youdroid** [comment]
I know why now. I think the release dates of the episodes are not yet announced or not up to date in sickchill. All the TV Shows have the date of 2020-06-27, that's why they are all stuck together and considered as a single episode.
I will find out how to handle this

**Comment by youdroid** [comment]
Hi,
I fixed it in [V1.0.1](https://github.com/youdroid/home-assistant-sickchill/releases/tag/V1.0.1)

Thanks for your feedback !
Do not hesitate to give me your other different feedback with the use of this component. :sunglasses:

**Comment by kobbra** [comment]
Hi

Yes but i actually think data from sickchill is ok, its not uncommon that netflix and amazon release entire seasons at the same day. if i look at sickchill its just treats them as separate episodes with same release date.. but maybe just showing ep1 is better, less spam :) 

btw i wanted to ask if there is a possibility to sort the data somehow.. now it seems to be on title but sorting by date would be nice :)

**Comment by youdroid** [comment]
It's in progress, and it's coming soon 😎
I have nearly finished. 

Btw about entire seasons at the same day, I will display all episode (one per line), if this possible.
it will be more user friendly, I think
