### ISSUE TITLE
Sickchill using web_Root

### ISSUE THREAD

**Issue by m1ckyb** [youdroid/home-assistant-sickchill#7]
Hi,

I use sickchill behind a reverse proxy, so i have chnaged my web_root option in config.ini (web_root = "/sickchill"

This means the component cannot find my sickchill instance as it isn't running on the base url (xxx.xxx.xxx.xxx:8081) instead running on (xxx.xxx.xxx.xxx:8081/sickchill/) any chance of getting a option for this

Thanks

**Comment by youdroid** [comment]
Hi,

Yes, I can add a parameter in the configuration to take into account the web root url of your sickchill.

I will add it in the next release.
I will notify you when it's done !

**Comment by youdroid** [comment]
Sorry for the delay i will be working on this in the next 2 weeks !

Best regards

**Comment by m1ckyb** [comment]
> 
> 
> Sorry for the delay i will be working on this in the next 2 weeks !
> 
> Best regards

Hi,

thanks for the update :+1:

**Comment by youdroid** [comment]
Hi,
It's now available in the new release [V1.2](https://github.com/youdroid/home-assistant-sickchill/releases/tag/V1.2)

Thanks for your support!
Do not hesitate to give me your other different feedback with the use of this component. :sunglasses:

**Comment by m1ckyb** [comment]
Thank you so much, it works perfectly.. 👍
