### ISSUE TITLE
a show not visable

### ISSUE THREAD

**Issue by turnmike2** [youdroid/home-assistant-sickchill#9]
Hi, 
I have a Medusa installation and see  the right info in HA. 
But somehow one dutch show is somehow not taken into account in the list. And is invisable.
I Don't know exactly how to troubleshoot it.  
Any idea how to verify it?
Overall it looks quite good...
Thanks for any troubleshooting info.

**Comment by youdroid** [comment]
Hi!

Sorry my I don't know Medusa, from what I've read it looks a lot like SickChill ( a fork ? )
But I don't quite understand your problem. Are you using Medusa and using this sickchill integration? And it works?

**Comment by turnmike2** [comment]
Basically everything cones from sickbeard - > sickrage. Then the system were forked into sickchill and medusa.
Used all 4 of them. But the basis are the same. Previously using sickchill I already noticed at least one show not to be present. It's called "klem". Show starts again tomorrow, but can't see in in HA. Other shows I do see. And this is why I'd like to verify why it does not show. Any ideas?

**Comment by youdroid** [comment]
Thank you for all this information.
I did not know all of these forks.
And in your opinion what is the best of all?

Okay, well I will see why this specific series is not picked up in the integration and is not showing in HA.

I'll keep you posted!

**Comment by youdroid** [comment]
I found why your TV series does not appear in your HA.
I tested with your TV series, and it does not appear in my HA too.

You should know about displaying TV shows in AH I use API calls. In the return of the sickchill API, the TV shows "klem" does not have an air date, which is why it does not appear in HA.

Unfortunately I use this date to display the TV shows or not in HA, as this TV shows has no date it is not displayed.

**Comment by turnmike2** [comment]
hmm..

Perhaps I am missing something, but the picture shows actually an air date...
![image](https://user-images.githubusercontent.com/58710889/94060300-07981680-fde4-11ea-9912-ef7eb2ff215a.png)

To get back at your question: At this moment I really like medusa. Using it not very long yet, but some options in the front-end are really looking good... Also it allready has moved fully into py3. Not using it allready for a long time, but for now it looks nice and bit more usefull.

**Comment by youdroid** [comment]
I agree with you, I observed the same thing on the interface.
The release date is present on the web interface, but in the call API release date is empty. 
I am confused about your problem, but I can't give you solution for now.

Thanks for your feedback on Medusa.
What is the most problematic for me in Sickchill is the interface, I do not find it very intuitive and not very pretty.
And I often have startup problems after updates.

But I have the impression that Medusa has much the same user interface?
I'll watch anyway on the side of medusa.

Sorry for not being able to fix your problem ...

**Comment by turnmike2** [comment]
No Problem. 
Searching a bit deeper it looks like it is a Sickchill/Medusa problem.
The API call does not present the show anyway.
Whenever I do the following: <IP><PORT>/api/<API_ID>/?cmd=shows 
The show is not presented at all. So you will not be able to query it. 
 Interesting though is how SickChill shows the data itself. 
It will be weird to have a show internally present, not being able to result it to the API.
I changed the example to a different indexer. Which is presenting the  correct information.
<IP><PORT>/api/<API_ID>/?cmd=show.seasons&indexerid=321148   <-- is the ID coming from thetvdb.com. 

From my point of view. Not a "HA-sichchill" issue. So if you have idea's to share, please do. Otherwise we can close :-)

ps user inferace is a bit tweaked. Option "manual search" gives all known results. The re-search option in Sickchill allways made me struggle which one I needed to use.  Probably more nice enhancements are available. Just try.

Thanks for now!

**Comment by IDmedia** [comment]
I'm also using Medusa and forked this module as I wanted to add a few more tweaks and support for flex-table-card.
Instead of airdate I'm using the full airdate/time and I'm also pulling data from the same endpoint as Medusa uses in order to generate the schedule/ view. You might want to give it a try. All credit goes to youdroid :)

https://git.idmedia.no/home-assistant/hass-medusa

**Comment by youdroid** [comment]
Hi!

Good idea to develop a specific integration Medusa.

I will look at the flex-table-card side, this card looks very interesting thank you.

If you develop new features that can be interesting, don't hesitate to share them with me :sunglasses:
